runtime: nodejs18

env_variables:
  MONGODB_URI: mongodb+srv://Greenaiservices:Greenaiservices123@greenaiservice.wnvrtaa.mongodb.net/greenai
  PORT: 5000
  JWT_SECRET: yourrandomsecret
  JWT_EXPIRES_IN: "90d"
  NODE_ENV: "development"

automatic_scaling:
  min_instances: 1
  max_instances: 10

instance_class: F2
