runtime: nodejs16

env_variables:
MONGODB_URI: "mongodb+srv://Greenaiservices:Greenaiservices123@greenaiservice.wnvrtaa.mongodb.net/greenai"

automatic_scaling:
  min_instances: 1
  max_instances: 10

instance_class: F2
